openapi: "3.0.3"
info:
  title: "CrystalCall API"
  description: "Backend for CrystalCall"
  version: "1.0.0"
servers:
  - url: "https://crystalcall-server.webo.daimones.xyz"
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: Logs in users.
      description: Logs in users.
      produces:
        - application/json
      parameters:
        - in: formData
          name: email
          description: Email of the user
          required: true
          type: string
        - in: formData
          name: password
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: OK
        422:
          description: Unprocessable entity
  /signup:
    post:
      tags:
        - Authentication
      summary: Register users.
      description: Creates new users.
      produces:
        - application/json
      parameters:
        - in: formData
          name: email
          description: Email of the user
          required: true
          type: string
        - in: formData
          name: password
          description: Password of the user
          required: true
          type: string
      responses:
        201:
          description: Created
        400:
          description: Bad request
components:
  schemas: {}