ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080
jwt:
  issuer: "https://crystalcall-server.daimones.xyz"
  audience: "https://crystalcall-server.daimones.xyz"
  realm: "Crystalcall app"

